// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf03F3qfeoEqnGLWSVDDporGuOA0MHzvw',
    appId: '1:83545647184:web:a7204a127db217a0118955',
    messagingSenderId: '83545647184',
    projectId: 'notes-flutter-first',
    authDomain: 'notes-flutter-first.firebaseapp.com',
    storageBucket: 'notes-flutter-first.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiAlGzeW7eveztsdd0BNm1wIMJyrtWbds',
    appId: '1:83545647184:android:f8bedad87f2c3b42118955',
    messagingSenderId: '83545647184',
    projectId: 'notes-flutter-first',
    storageBucket: 'notes-flutter-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkA-k7HHBVFWfSTaXHEnjQsohfrweHqUo',
    appId: '1:83545647184:ios:6183f7bb9004ce36118955',
    messagingSenderId: '83545647184',
    projectId: 'notes-flutter-first',
    storageBucket: 'notes-flutter-first.appspot.com',
    iosClientId: '83545647184-vhc2sqmncltk0diq0m67tm6etjou2an5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutter',
  );
}
